<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LIN65004458" failures="1" tests="8" name="HomeLoan" time="0.088" errors="0" timestamp="2025-01-29T14:43:25 IST">
  <testcase classname="testNGDemo.Demo1Test" name="demo1" time="0.005"/>
  <testcase classname="testNGDemo.Demo1Test" name="secondTest" time="0.003"/>
  <testcase classname="testNGDemo.Demo1Test" name="testfailListener" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGDemo.Demo1Test.testfailListener(Demo1Test.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testfailListener -->
  <testcase classname="testNGDemo.Demo2" name="Login" time="0.001"/>
  <testcase classname="testNGDemo.Demo2" name="Login" time="0.001"/>
  <testcase classname="testNGDemo.Demo2" name="Login" time="0.001"/>
  <testcase classname="testNGDemo.Demo2" name="demo2" time="0.002"/>
  <testcase classname="testNGDemo.Demo4" name="APILoginPersonalLoan" time="0.002"/>
  <testcase classname="testNGDemo.Demo4" name="MobileLoginPersonalLoan" time="0.0">
    <ignored/>
  </testcase> <!-- MobileLoginPersonalLoan -->
  <testcase classname="testNGDemo.Demo4" name="WebLoginPersonalLoan" time="0.0">
    <ignored/>
  </testcase> <!-- WebLoginPersonalLoan -->
  <testcase classname="testNGDemo.Demo4" name="testingTest" time="0.0">
    <ignored/>
  </testcase> <!-- testingTest -->
</testsuite> <!-- HomeLoan -->
